sudo: false
dist: trusty

addons:
  apt:
    packages:
      xserver-xorg-dev

language:
  - cpp

install:
  - git clone https://github.com/glfw/glfw && mkdir build && cd build && cmake ../glfw && make -j4 && sudo make install

script:
  - cmake .
  - make
