sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libvulkan-dev
      - xorg-dev
      - xserver-xorg-dev

language:
  - cpp

install:
  - git clone https://github.com/glfw/glfw glfw
  - cd glfw
  - cmake .
  - make -j4
  - sudo make install
  - cd ~/build/fluffels/vulkan-experiments

script:
  - cmake .
  - make
