sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libglm-dev
      - xorg-dev

language:
  - cpp

env:
  - CMAKE_CXX_STANDARD=17

install:
  - git clone https://github.com/glfw/glfw glfw
  - cd glfw
  - cmake .
  - make -j4
  - sudo make install
  - cd ~/build/fluffels/vulkan-experiments
  - git clone https://github.com/g-truc/glm.git glm
  - cd glm
  - git checkout 0.9.8
  - cmake .
  - make -j4
  - sudo make install
  - cd ~/build/fluffels/vulkan-experiments
  - wget https://sdk.lunarg.com/sdk/download/1.0.65.0/linux/vulkansdk-linux-x86_64-1.0.65.0.run
  - chmod +x vulkansdk-linux-x86_64-1.0.65.0.run
  - ./vulkansdk-linux-x86_64-1.0.65.0.run
  - source VulkanSDK/1.0.65.0/setup-env.sh

script:
  - cmake .
  - make
